### ISSUE TITLE
Error on Apple M1 Sonoma building python-scipy

### ISSUE THREAD

**Issue by dkapitan** [b-data/data-science-devcontainers#6]
Thanks for this excellent collection of devcontainers @benz0li ! I have spend quite some time trying to get my Apple M1 setup to work, and this saved my day.

Running base Python works out of the box, however, when building Python Scipy I get the following error (excerpt from log):

```
[2024-02-27T07:06:17.481Z] Dev Containers 0.338.1 in VS Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda).
[2024-02-27T07:06:17.481Z] Start: Resolving Remote
[2024-02-27T07:06:17.484Z] Setting up container for folder or workspace: /Users/dkapitan/git/dkapitan/data-science-devcontainers
[2024-02-27T07:06:17.484Z] Context: desktop-linux
[2024-02-27T07:06:17.485Z] Start: Check Docker is running
[2024-02-27T07:06:17.485Z] Start: Run: docker version
[2024-02-27T07:06:17.569Z] Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:04:20 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.26.1 (131620)
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:15 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
[2024-02-27T07:06:17.571Z] Stop (86 ms): Run: docker version
[2024-02-27T07:06:17.571Z] Stop (86 ms): Check Docker is running
[2024-02-27T07:06:17.571Z] Start: Run: docker volume ls -q
[2024-02-27T07:06:17.614Z] Stop (43 ms): Run: docker volume ls -q
[2024-02-27T07:06:17.614Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/dkapitan/git/dkapitan/data-science-devcontainers --filter label=vsch.quality=stable
[2024-02-27T07:06:17.658Z] Stop (44 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/Users/dkapitan/git/dkapitan/data-science-devcontainers --filter label=vsch.quality=stable
[2024-02-27T07:06:17.658Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/dkapitan/git/dkapitan/data-science-devcontainers --filter label=devcontainer.config_file=/Users/dkapitan/git/dkapitan/data-science-devcontainers/.devcontainer/python-scipy/devcontainer.json
[2024-02-27T07:06:17.702Z] Stop (44 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/dkapitan/git/dkapitan/data-science-devcontainers --filter label=devcontainer.config_file=/Users/dkapitan/git/dkapitan/data-science-devcontainers/.devcontainer/python-scipy/devcontainer.json
[2024-02-27T07:06:17.702Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/dkapitan/git/dkapitan/data-science-devcontainers
[2024-02-27T07:06:17.745Z] Stop (43 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/dkapitan/git/dkapitan/data-science-devcontainers
[2024-02-27T07:06:17.745Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/dkapitan/git/dkapitan/data-science-devcontainers
[2024-02-27T07:06:17.790Z] Stop (45 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/dkapitan/git/dkapitan/data-science-devcontainers
[2024-02-27T07:06:17.791Z] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/dkapitan/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /Users/dkapitan/git/dkapitan/data-science-devcontainers --id-label devcontainer.local_folder=/Users/dkapitan/git/dkapitan/data-science-devcontainers --id-label devcontainer.config_file=/Users/dkapitan/git/dkapitan/data-science-devcontainers/.devcontainer/python-scipy/devcontainer.json --log-level debug --log-format json --config /Users/dkapitan/git/dkapitan/data-science-devcontainers/.devcontainer/python-scipy/devcontainer.json --mount-workspace-git-root
[2024-02-27T07:06:17.952Z] @devcontainers/cli 0.56.0. Node.js v18.17.1. darwin 23.3.0 arm64.
[2024-02-27T07:06:17.952Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/dkapitan/git/dkapitan/data-science-devcontainers --filter label=devcontainer.config_file=/Users/dkapitan/git/dkapitan/data-science-devcontainers/.devcontainer/python-scipy/devcontainer.json
[2024-02-27T07:06:17.994Z] Stop (42 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/dkapitan/git/dkapitan/data-science-devcontainers --filter label=devcontainer.config_file=/Users/dkapitan/git/dkapitan/data-science-devcontainers/.devcontainer/python-scipy/devcontainer.json
[2024-02-27T07:06:17.997Z] Stop (206 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/dkapitan/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /Users/dkapitan/git/dkapitan/data-science-devcontainers --id-label devcontainer.local_folder=/Users/dkapitan/git/dkapitan/data-science-devcontainers --id-label devcontainer.config_file=/Users/dkapitan/git/dkapitan/data-science-devcontainers/.devcontainer/python-scipy/devcontainer.json --log-level debug --log-format json --config /Users/dkapitan/git/dkapitan/data-science-devcontainers/.devcontainer/python-scipy/devcontainer.json --mount-workspace-git-root
[2024-02-27T07:06:17.997Z] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/dkapitan/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/dkapitan/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-3bbe0844-e3a8-48db-877a-1d75964884761709017577025 --workspace-folder /Users/dkapitan/git/dkapitan/data-science-devcontainers --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/dkapitan/git/dkapitan/data-science-devcontainers --id-label devcontainer.config_file=/Users/dkapitan/git/dkapitan/data-science-devcontainers/.devcontainer/python-scipy/devcontainer.json --log-level debug --log-format json --config /Users/dkapitan/git/dkapitan/data-science-devcontainers/.devcontainer/python-scipy/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-02-27T07:06:18.158Z] @devcontainers/cli 0.56.0. Node.js v18.17.1. darwin 23.3.0 arm64.
[2024-02-27T07:06:18.158Z] Start: Run: docker buildx version
[2024-02-27T07:06:18.320Z] Stop (162 ms): Run: docker buildx version
[2024-02-27T07:06:18.321Z] github.com/docker/buildx v0.12.0-desktop.2 c5a13b51c1ae9358eb691e9a21c955590e26d0a0
[2024-02-27T07:06:18.321Z] 
[2024-02-27T07:06:18.321Z] Start: Resolving Remote
[2024-02-27T07:06:18.323Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/dkapitan/git/dkapitan/data-science-devcontainers --filter label=devcontainer.config_file=/Users/dkapitan/git/dkapitan/data-science-devcontainers/.devcontainer/python-scipy/devcontainer.json
[2024-02-27T07:06:18.371Z] Stop (48 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/dkapitan/git/dkapitan/data-science-devcontainers --filter label=devcontainer.config_file=/Users/dkapitan/git/dkapitan/data-science-devcontainers/.devcontainer/python-scipy/devcontainer.json
[2024-02-27T07:06:18.373Z] Start: Run: docker inspect --type image glcr.b-data.ch/python/scipy:3.12.2
[2024-02-27T07:06:18.421Z] Stop (48 ms): Run: docker inspect --type image glcr.b-data.ch/python/scipy:3.12.2
[2024-02-27T07:06:18.573Z] Start: Run: docker-credential-desktop get
[2024-02-27T07:06:18.609Z] Stop (36 ms): Run: docker-credential-desktop get
[2024-02-27T07:06:19.197Z] Resolving Feature dependencies for 'ghcr.io/devcontainers/features/common-utils:2'...
[2024-02-27T07:06:19.197Z] * Processing feature: ghcr.io/devcontainers/features/common-utils:2
[2024-02-27T07:06:19.385Z] Start: Run: docker-credential-desktop get
[2024-02-27T07:06:19.409Z] Stop (24 ms): Run: docker-credential-desktop get
[2024-02-27T07:06:19.954Z] Resolving Feature dependencies for 'ghcr.io/devcontainers/features/docker-outside-of-docker:1'...
[2024-02-27T07:06:19.954Z] * Processing feature: ghcr.io/devcontainers/features/docker-outside-of-docker:1
[2024-02-27T07:06:20.366Z] * Processing feature: ghcr.io/devcontainers/features/common-utils
[2024-02-27T07:06:20.774Z] Resolving Feature dependencies for 'ghcr.io/rocker-org/devcontainer-features/apt-packages:1'...
[2024-02-27T07:06:20.774Z] * Processing feature: ghcr.io/rocker-org/devcontainer-features/apt-packages:1
[2024-02-27T07:06:21.426Z] * Processing feature: ghcr.io/devcontainers/features/common-utils
[2024-02-27T07:06:21.733Z] * Fetching feature: common-utils_0_oci
[2024-02-27T07:06:22.093Z] * Fetched feature: common-utils_0_oci version 2.4.2
[2024-02-27T07:06:22.093Z] * Fetching feature: docker-outside-of-docker_1_oci
[2024-02-27T07:06:22.416Z] * Fetched feature: docker-outside-of-docker_1_oci version 1.4.2
[2024-02-27T07:06:22.416Z] * Fetching feature: apt-packages_2_oci
[2024-02-27T07:06:22.725Z] * Fetched feature: apt-packages_2_oci version 1.0.2
[2024-02-27T07:06:22.728Z] Start: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/0r/g9sj6_z95_70k7_pn0h5v0qc0000gn/T/devcontainercli/container-features/0.56.0-1709017579195/Dockerfile-with-features -t vsc-data-science-devcontainers-1965fd3b299b55e43f9a7890c6a5cb9c024481035f53f3f9db49b17121f34152 --target dev_containers_target_stage --build-arg BUILD_ON_IMAGE=glcr.b-data.ch/python/scipy --build-arg PYTHON_VERSION=3.12.2 --build-arg JUPYTERLAB_VERSION=4.1.2 --build-arg NODE_VERSION=18.19.1 --build-arg USE_ZSH_FOR_ROOT=unset-to-use-bash --build-arg SET_LANG=en_US.UTF-8 --build-arg SET_TZ=Etc/UTC --build-context dev_containers_feature_content_source=/var/folders/0r/g9sj6_z95_70k7_pn0h5v0qc0000gn/T/devcontainercli/container-features/0.56.0-1709017579195 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /Users/dkapitan/git/dkapitan/data-science-devcontainers/.devcontainer

(...)

[2024-02-27T07:09:12.051Z] Dockerfile-with-features:49
--------------------
  48 |     
  49 | >>> RUN dpkgArch="$(dpkg --print-architecture)" \
  50 | >>>   ## Ensure that common CA certificates
  51 | >>>   ## and OpenSSL libraries are up to date
  52 | >>>   && apt-get update \
  53 | >>>   && apt-get -y install --no-install-recommends --only-upgrade \
  54 | >>>     ca-certificates \
  55 | >>>     openssl \
  56 | >>> ## Install Python related stuff
  57 | >>>   ## Install JupyterLab
  58 | >>>   && pip install --no-cache-dir \
  59 | >>>     jupyterlab=="$JUPYTERLAB_VERSION" \
  60 | >>>     jupyterlab-git \
  61 | >>>     jupyterlab-lsp \
  62 | >>>     notebook \
  63 | >>>     nbclassic \
  64 | >>>     nbconvert \
  65 | >>>     "python-lsp-server[all]" \
  66 | >>>   && if ! echo "$BUILD_ON_IMAGE" | grep -q "python/base"; then \
  67 | >>>     pip install --no-cache-dir \
  68 | >>>       ipympl \
  69 | >>>       ipywidgets \
  70 | >>>       widgetsnbextension; \
  71 | >>>       ## Install facets
[2024-02-27T07:09:12.051Z] 
  72 | >>>       cd /tmp; \
  73 | >>>       git clone https://github.com/PAIR-code/facets.git; \
  74 | >>>       jupyter nbextension install facets/facets-dist/ --sys-prefix; \
  75 | >>>   fi \
  76 | >>>   ## Clean up
  77 | >>>   && rm -rf /tmp/* \
[2024-02-27T07:09:12.051Z]   78 | >>>     /root/.cache \
  79 | >>> ## Dev Container only
  80 | >>>   ## Install hadolint
  81 | >>>   && case "$dpkgArch" in \
  82 | >>>     amd64) tarArch="x86_64" ;; \
  83 | >>>     arm64) tarArch="arm64" ;; \
[2024-02-27T07:09:12.051Z]   84 | >>>     *) echo "error: Architecture $dpkgArch unsupported"; exit 1 ;; \
[2024-02-27T07:09:12.051Z]   85 | >>>   esac \
  86 | >>>   && apiResponse="$(curl -sSL \
[2024-02-27T07:09:12.051Z]   87 | >>>     https://api.github.com/repos/hadolint/hadolint/releases/latest)" \
[2024-02-27T07:09:12.051Z]   88 | >>>   && downloadUrl="$(echo "$apiResponse" | grep -e \
  89 | >>>     "browser_download_url.*Linux-$tarArch\"" | cut -d : -f 2,3 | tr -d \")" \
  90 | >>>   && echo "$downloadUrl" | xargs curl -sSLo /usr/local/bin/hadolint \
  91 | >>>   && chmod 755 /usr/local/bin/hadolint \
  92 | >>>   ## Create backup of root directory
  93 | >>>   && cp -a /root /var/backups \
  94 | >>>   ## Clean up
  95 | >>>   && rm -rf /var/lib/apt/lists/*
  96 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c dpkgArch=\"$(dpkg --print-architecture)\"   && apt-get update   && apt-get -y install --no-install-recommends --only-upgrade     ca-certificates     openssl   && pip install --no-cache-dir     jupyterlab==\"$JUPYTERLAB_VERSION\"     jupyterlab-git     jupyterlab-lsp     notebook     nbclassic     nbconvert     \"python-lsp-server[all]\"   && if ! echo \"$BUILD_ON_IMAGE\" | grep -q \"python/base\"; then     pip install --no-cache-dir       ipympl       ipywidgets       widgetsnbextension;
[2024-02-27T07:09:12.051Z]        cd /tmp;       git clone https://github.com/PAIR-code/facets.git;       jupyter nbextension install facets/facets-dist/ --sys-prefix;   fi   && rm -rf /tmp/*     /root/.cache   && case \"$dpkgArch\" in     amd64) tarArch=\"x86_64\" ;;     arm64) tarArch=\"arm64\" ;;     *) echo \"error: Architecture $dpkgArch unsupported\"; exit 1 ;;   esac   && apiResponse=\"$(curl -sSL     https://api.github.com/repos/hadolint/hadolint/releases/latest)\"   && downloadUrl=\"$(echo \"$apiResponse\" | grep -e     \"browser_download_url.*Linux-$tarArch\\\"\" | cut -d : -f 2,3 | tr -d \\\")\"   && echo \"$downloadUrl\" | xargs curl -sSLo /usr/local/bin/hadolint   && chmod 755 /usr/local/bin/hadolint   && cp -a /root /var/backups   && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 1
[2024-02-27T07:09:12.055Z] Stop (169327 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/0r/g9sj6_z95_70k7_pn0h5v0qc0000gn/T/devcontainercli/container-features/0.56.0-1709017579195/Dockerfile-with-features -t vsc-data-science-devcontainers-1965fd3b299b55e43f9a7890c6a5cb9c024481035f53f3f9db49b17121f34152 --target dev_containers_target_stage --build-arg BUILD_ON_IMAGE=glcr.b-data.ch/python/scipy --build-arg PYTHON_VERSION=3.12.2 --build-arg JUPYTERLAB_VERSION=4.1.2 --build-arg NODE_VERSION=18.19.1 --build-arg USE_ZSH_FOR_ROOT=unset-to-use-bash --build-arg SET_LANG=en_US.UTF-8 --build-arg SET_TZ=Etc/UTC --build-context dev_containers_feature_content_source=/var/folders/0r/g9sj6_z95_70k7_pn0h5v0qc0000gn/T/devcontainercli/container-features/0.56.0-1709017579195 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /Users/dkapitan/git/dkapitan/data-science-devcontainers/.devcontainer
[2024-02-27T07:09:12.058Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/0r/g9sj6_z95_70k7_pn0h5v0qc0000gn/T/devcontainercli/container-features/0.56.0-1709017579195/Dockerfile-with-features -t vsc-data-science-devcontainers-1965fd3b299b55e43f9a7890c6a5cb9c024481035f53f3f9db49b17121f34152 --target dev_containers_target_stage --build-arg BUILD_ON_IMAGE=glcr.b-data.ch/python/scipy --build-arg PYTHON_VERSION=3.12.2 --build-arg JUPYTERLAB_VERSION=4.1.2 --build-arg NODE_VERSION=18.19.1 --build-arg USE_ZSH_FOR_ROOT=unset-to-use-bash --build-arg SET_LANG=en_US.UTF-8 --build-arg SET_TZ=Etc/UTC --build-context dev_containers_feature_content_source=/var/folders/0r/g9sj6_z95_70k7_pn0h5v0qc0000gn/T/devcontainercli/container-features/0.56.0-1709017579195 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /Users/dkapitan/git/dkapitan/data-science-devcontainers/.devcontainer
[2024-02-27T07:09:12.058Z]     at Y$ (/Users/dkapitan/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js:465:1933)
[2024-02-27T07:09:12.058Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-02-27T07:09:12.058Z]     at async Fw (/Users/dkapitan/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js:464:1831)
[2024-02-27T07:09:12.058Z]     at async $J (/Users/dkapitan/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js:464:608)
[2024-02-27T07:09:12.058Z]     at async tAA (/Users/dkapitan/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js:481:3660)
[2024-02-27T07:09:12.058Z]     at async CC (/Users/dkapitan/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js:481:4775)
[2024-02-27T07:09:12.058Z]     at async NeA (/Users/dkapitan/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js:614:11107)
[2024-02-27T07:09:12.058Z]     at async MeA (/Users/dkapitan/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js:614:10848)
[2024-02-27T07:09:12.061Z] Stop (174064 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/dkapitan/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/dkapitan/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-3bbe0844-e3a8-48db-877a-1d75964884761709017577025 --workspace-folder /Users/dkapitan/git/dkapitan/data-science-devcontainers --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/dkapitan/git/dkapitan/data-science-devcontainers --id-label devcontainer.config_file=/Users/dkapitan/git/dkapitan/data-science-devcontainers/.devcontainer/python-scipy/devcontainer.json --log-level debug --log-format json --config /Users/dkapitan/git/dkapitan/data-science-devcontainers/.devcontainer/python-scipy/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-02-27T07:09:12.061Z] Exit code 1
[2024-02-27T07:09:12.063Z] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/dkapitan/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/dkapitan/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-3bbe0844-e3a8-48db-877a-1d75964884761709017577025 --workspace-folder /Users/dkapitan/git/dkapitan/data-science-devcontainers --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/dkapitan/git/dkapitan/data-science-devcontainers --id-label devcontainer.config_file=/Users/dkapitan/git/dkapitan/data-science-devcontainers/.devcontainer/python-scipy/devcontainer.json --log-level debug --log-format json --config /Users/dkapitan/git/dkapitan/data-science-devcontainers/.devcontainer/python-scipy/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-02-27T07:09:12.063Z] Exit code 1
```

I am trying to figure out what the error is, but can't really see it. Any help would be appreciated.

**Comment by benz0li** [comment]
@dkapitan Good catch.

Will be fixed immediately.
